[package]
name = "pepe_core"
version = "0.1.0"
edition = "2021"

[lib]
name = "pepe_core"
path = "src/lib.rs"

[dependencies]
winit = "0.27"
env_logger = "0.10"
log = "0.4"
wgpu = "0.17.0"
pollster = "0.3.0"

imgui = "0.11"
imgui-wgpu = "0.24"
imgui-winit-support = "0.11"
 