[package]
name = "salon_core"
version = "0.1.0"
edition = "2021"

[lib]
name = "salon_core"
path = "src/lib.rs"

[dependencies]
wgpu = "0.17.0"
serde_json = "1.0"
bytemuck = "1.7.1"
half = "2.3.1"
zune-jpeg = "0.3.17"
