name: test suite
on: [push, pull_request]

jobs:
  test:
    name: cargo test
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      # - run: sudo apt-get install librust-atk-dev
      # - run: sudo apt-get install libgtk-3-dev
      - run: cargo test -p salon_tests